from pathlib import Path
import json
P=Path(__file__).resolve().parents[1];O=P/'research_v34';N=P/'research_v35';N.mkdir(exist_ok=True)
assert not (N/'results/preparation_manifest.json').exists()
def write(n,s):(N/n).write_text(s,encoding='utf-8')
c0=json.loads((O/'protocol.json').read_text(encoding='utf-8'));c={k:c0[k] for k in ['label_end','windows','seeds','neural','probe','offset_probe','report_python','decision_dates']}
arms={'annual':'rolling5_annual20','add':'fixed_transform_add_only','remove':'fixed_transform_remove_only','both':'fixed_transform_step100'}
contrasts=[('add','annual'),('remove','annual'),('both','remove'),('both','add'),('both','annual')]
pairs=[dict(history=arms[a],candidate=m,reference_history=arms[b],reference=m,metric=loss) for a,b in contrasts for m in ['learned_vol_interaction','learned_order_extension','learned_order_offset'] for loss in ['direction_error','brier']]
c.update(version=35,experiment='Controlled addition and removal of rolling-window training members in fixed annual coordinates',arms=arms,policies=c0['policies']+[arms['add'],arms['remove']],primary_comparisons_per_window=pairs,
  memberships='At each quarter cutoff q and preceding annual cutoff a, define A=rolling5 training members at a, Q=rolling5 members at q, N=Q minus A newly eligible members, O=A minus Q removed members, R=A intersect Q. Four arms: annual=A; add=A union Q=A union N; remove=A intersect Q=A minus O; both=Q. Sorted unique row identities, no duplication or resampling. Reset A each new year. At December all arms identical. A/Q use anchor date >=cutoff-5calendarYears+1day and joint_completed<=cutoff; includes all eligible weekdays. All ablation members must be mature by q. Added means newly eligible relative to annual set, including previously dated samples with newly matured labels. Add-only preserves old lower bound during that year and can exceed5years; remove-only adds no postannual members and has fewer observations. These are controlled membership interventions, not all fixed5year policies.',
  fixed_coordinates=c0['fixed_coordinates'],
  fitting='New fits only add and remove arms at17nonDecembercutoffs x3seeds x4learnedmethods=408 endpoints /102jobs. Use R34 fixed-coordinate full-step fit_coefficients verbatim and identical probe/offset settings. No coefficient shrinkage, alpha search or new calibration. R18/R19/R23 fully optimize own coefficients on fixed annual design; R25 freezes same-arm same-cutoff R19 and fully fits scalar gamma. Reuse72annualheads and204full-roll R34endpoints exactly. R34 full-step predictions preserved exactly; do not substitute R32 updated transformations or R34 step25 as the both arm.',
  controls='Same272weeks and11 unchanged old policies. Each new arm native_MSE exactly annual native (no invented probability). Training-frequency control uses that arm own causal training label mean at each cutoff, not full-roll frequency. Learned probabilities are three-seed equal mean, strict>.5; signal cutoff strictly precedes signal date. Q1 all rows equal annual. All18rawannualfeaturebanks reused without new inference; each treatment training interface selects only its allowed members.',
  probability_accounting='Four probabilities at each identical seed-week: p0 annual, pA add-only, pR remove-only, pB both. Conditional add effects pA-p0 and pB-pR; conditional removal effects pR-p0 and pB-pA. Nonadditive remainder pB-pA-pR+p0. Average both operation orders: add_effect=.5*((pA-p0)+(pB-pR)); remove_effect=.5*((pR-p0)+(pB-pA)), sum exactly pB-p0. Compute from each seed actual sigmoid then average contributions, matching original ensemble. Never sigmoid(mean seed logit). These are specified order-averaged training-operation effects under fixed recipe; conditional effects also reported. Nonadditivity includes refitting and sigmoid, and is not the market/order feature interaction.',
  coefficient_accounting='For each nonDecembercutoff,seed,method reconstruct the same four coefficient vectors in annual standardized coordinates. Record both conditional changes, order-average changes and nonadditive vector; report coordinatewise changes, intercept, full-vector norms. These explain coefficient differences without attributing performance to coefficient norm alone. All vectors retain full same-arm R25/R19 offset relation.',
  reporting='Report all methods, seeds, years, two147/125periods and descriptive272pooledperiod. Probability effect summaries for all weeks and cases defined by both full-roll vs annual: regression/recovery/stable_correct/stable_wrong. Outcome-signed effects use (2actual_up-1)*deltaP, negative adverse. Dominant adverse add/remove only if < -1e-12, ties marked, no misleading share denominator. Include all2026weeks and flips for all3 altered arms, not only previously identified bad weeks. Freeze unlabelled seed effects before outcome summaries.',
  inference='60 contrasts jointly Holm:2periods x3mainrecipes x2losses x5prespecifiededges (add vs annual; remove vs annual; both vs remove; both vs add; both vs annual). Same10000circular8-observationbootstrap seed20260910, centered two-sided p, marginal95CI. Both vs annual overlaps prior round, not independent evidence. Old60R34comparisons archived unchanged. No across-round correction, no performance-dependent arm selection.',
  sequencing='Freeze protocol, all sources, all input hashes and5063oldfiles. Independently verify memberships, set-operation identities, maturity/quarter boundaries, source cache hashes, descriptor algebra and synthetic probability/vector accounting. Fit all408new endpoints before weekly scoring; freeze then score all new arms, evaluate, diagnose, independently verify and report. No revised protocol after seeing results.',
  verification='Independent L-BFGS-B and Brent for all408new plus204reused full-roll endpoints. Reconstruct annual coordinates; verify all153training interfaces by poisoning excluded features, descriptors and labels. Independent scalar probability and seed averaging, annual Q1 parity and own-arm frequencies. Verify all coefficient and probability effects and nonadditivity with alternate order-averaging algebra. Independent metric arithmetic and all60bootstrap/Holm contrasts. All5063oldfiles remain unchanged.',
  budgets=dict(old_files=5063,new_neural_fits=0,new_feature_inference=0,new_transform_fits=0,new_fit_jobs=102,new_head_fits=408,reused_full_roll_heads=204,reused_annual_heads=72,independent_endpoint_checks=612,weeks=272,model_rows=56576,ensemble_rows=21216,seed_effect_rows=3264,weekly_effect_rows=1088),
  limits='All272outcomes previously seen; exploratory research, no new blind evaluation. Membership intervention changes sample count, class proportions, support and the mean-loss sample weights; it does not separately identify quantity versus quality or an individual sample causal effect. Annual transforms trained with allA remain fixed even in remove-only, so removal is only from coefficient-fitting loss, not erasing old information from neural network or transformations. This intentionally tests conditional head-level member influence, not a full-pipeline leave-out claim. Order-average accounting not unique natural causal importance; keep both conditional paths. No proof of regime causality or general WFO failure; no automatic model promotion or live changes. Preserve old R25recent73/125=58.4%.')
write('protocol.json',json.dumps(c,ensure_ascii=False,indent=2))
s=(O/'evaluate34.py').read_text(encoding='utf-8').replace('common34','common35').replace('histories=11','histories=13');s=s.replace("m[m.method.isin(['learned_vol_interaction','native_mse','training_frequency'])]","m[m.method.isin(PRIMARY)&m.history.isin(list(ARMS.values()))&m.window.ne('pooled_2021_2026')]");write('evaluate35.py',s)
s=(O/'run34.py').read_text(encoding='utf-8').replace("'evaluate','verify'","'evaluate','diagnose','verify'").replace('{phase}34.py','{phase}35.py');write('run35.py',s)
s=(O/'delivery34.py').read_text(encoding='utf-8').replace('common34','common35').replace("'evaluation','report'","'evaluation','diagnosis','report'");write('delivery35.py',s)
# Keep independent route, raw descriptors and original-bank checks, now against the R35 frozen copies.
s=(O/'contract34.py').read_text(encoding='utf-8');s=s[:s.index('def coefficient_cases():')];s=s.replace('common34','common35').replace('def memberships_check():','def base_memberships_check():');write('base_contract35.py',s)
# Independent resampling verifier uses only the inherited, identical windows and bootstrap settings.
s=(O/'verify34.py').read_text(encoding='utf-8');start=s.index('def verify_inference(');end=s.index('\ndef main():',start);write('inference35.py','from common35 import *\n\n'+s[start:end]+'\n')
write('README.md','# 第三十五轮：滚动训练成员加入与移出的受控对照\n\n年度 A；只加入 A∪Q；只移出 A∩Q；同时操作 Q（复用 R34 固定年度变换、100% 系数更新）。各年重新定义 A。只改分类系数拟合成员；旧信息仍存在于固定年度神经网络和变换中。所有历史已查看。\n\n先冻结后运行：`research_v4/.venv_gpu/Scripts/python.exe -B -u research_v35/run35.py prepare contract fit score evaluate diagnose verify report`；图像审查后单独运行 `delivery35.py`。\n')
print('R35 protocol and adapted modules created; no new fit or weekly scoring.')
