from pathlib import Path
import json
P=Path(__file__).resolve().parents[1];O=P/'research_v32';N=P/'research_v33';N.mkdir(exist_ok=True)
def write(n,s):(N/n).write_text(s,encoding='utf-8')
c0=json.loads((O/'protocol.json').read_text(encoding='utf-8'));c={k:c0[k] for k in ['label_end','windows','seeds','report_python','decision_dates']}
c.update(version=33,experiment='Exact probability-change accounting for frozen annual versus quarterly head pipelines',reference='rolling5_annual20',candidate='annual_net_quarter_head',methods=['learned_market','learned_vol_interaction','learned_order_extension','learned_order_offset'],groups=['intercept','decoded','market','vol','order'],
    scope='All272canonicalweeklycases,4learnedmethods,3seeds. Focus2026all30weeks and all direction flips; also show everyyear and both frozen147/125periods. No newneural/headtraining, featureinference, candidatepolicy, weights, thresholdselection or inferentialtest. Recompute existing heads only to explain oldpredictions.',
    decomposition='For eachseed andweek reconstruct old/new logits from same annual rawdecodedfeatures and same rawmarket/orderdescriptors, but their own scalers,rays,projections andcoefficients. Partition into intercept,25decodedlinear,4marketlinear,volinteraction,orderinteraction; missinggroupszero. DeltaTerm exact newminusold. For product theta*x split symmetrically as .5*(thetaN-thetaA)*(xN+xA)+.5*(thetaN+thetaA)*(xN-xA); intercept entirelycoefficient. Coordinate split includes preprocessing/ray/projection changes and is parameterization-dependent, not single-parameter causality.',
    probability_accounting='Perseed secant w=(sigmoid(zN)-sigmoid(zA))/(zN-zA); abs(dz)<=1e-4 uses algebraically equivalent stable expm1 expression, dz=0 uses sigmoid derivative. GroupdeltaProbability=w*groupdeltaLogit, including coefficient/input splits. Average eachgroup over3seeds to recover the exact ensemble meanProbability difference. Never sigmoid(meanlogit). This is a specified straight-line allocation, not unique causal importance or permutationShapley. Opposing contributions can cancel; no percentage shares with nearzero denominators.',
    classification='Directions and actuallabels are read from frozen R32probabilities/predictions, strict>.5. regression=oldcorrect/newwrong; recovery=oldwrong/newcorrect; stable_correct/stable_wrong. Signed contribution=(2*y-1)*probabilityContribution; negative is adverse to realizedoutcome. Dominant adverse group is minimum signed contribution below-1e-12, firstgroup in frozenorder on ties; report ties. This is descriptive accounting, not independently significant feature selection.',
    training_window='For each23headcutoff compare annual neural/head training membership with quarterly headmembership: retained/added/removed rowsets, counts, upfrequencies, matured dates, meanreturns. Added includes newlymatured prior-calendar observations; not all new-quarter timestamps. Explicitly preserve allrows, including0changes atDecember. No claim that this membership change alone caused coefficient shifts without a controlled refit.',
    parameter_diagnostics='For eachcutoff/seed/method/group report coefficientnorm/deltanorm and intercept. For eachcutoff/seed compare rep/market clippingbounds,means,sd; vol/order rays,projections,residualmeans/sd. Norms across updated coordinates are diagnostics, not causal feature importance. No intervention that selectively freezes components is evaluated as a newpolicy.',
    outputs='seed_components16320rows; weekly_attribution1088rows; complete2026cases120rows and flips; all4methods/year/period performance parity; component signed probability contributions by case/year/period; training membership and scaler/projection summaries; all frozen R32 baseline metrics and28comparisons retained.',
    sequencing='Freeze protocol,sources,inputs and4895oldfiles before newcomponent decomposition. Contract checks source hashes/memberships and synthetic identities/nonlinearensemble example. Compute unlabelled perseed decomposition, compare archived probabilities, then join outcomes for descriptive summaries. Verify exact algebra with independently implemented coordinates/scalars and64nodeGaussLegendre integral of sigmoid derivative. No new performance selection.',
    verification='Independent transformation algebra, scalar group sums and symmetric product splits; probabilityweights checked by64nodequadrature; compare everyseed andensemble to R32archive, exactQ1zero attribution, coefficient/input additivity and totalprobabilityadditivity. Independently audit all membershipsets, summaries, parameters and source hashes. All4895oldfilespreserved.',
    limits='All outcomes already viewed. This is descriptive explanation of existing forecast changes, not a new strategy backtest or proof of market predictability. Terms and coefficient/input splits depend on selected coordinates/path; correlated regressors, projections andscaling can move attribution across terms. Largest adverse contribution need not be the sole or sufficient cause of a flip. Training sample shift does not isolate which samples caused a fitted change.',budgets=dict(old_files=4895,new_neural_fits=0,new_head_fits=0,new_feature_inference=0,seed_week_pairs=3264,seed_component_rows=16320,ensemble_week_pairs=1088))
write('protocol.json',json.dumps(c,indent=2,ensure_ascii=False))
s=(O/'run32.py').read_text(encoding='utf-8').replace("['prepare','contract','extract','fit','score','evaluate','verify','report']","['prepare','contract','diagnose','verify','report']").replace('{phase}32.py','{phase}33.py');write('run33.py',s)
s=(O/'delivery32.py').read_text(encoding='utf-8').replace('common32','common33').replace("['extraction','fitting','scoring','evaluation','report']","['diagnosis','report']");write('delivery33.py',s)
print('R33 diagnostic protocol and runner created; no decomposition yet.')
