"""Generate R30 protocol and adapted fixed evaluation sources before new scoring."""
from pathlib import Path
import json
P=Path(__file__).resolve().parents[1];O=P/'research_v29';N=P/'research_v30'
def write(name,s):(N/name).write_text(s,encoding='utf-8')
old=json.loads((O/'protocol.json').read_text(encoding='utf-8'));c={k:old[k] for k in ['label_end','windows','seeds','neural','probe','offset_probe','features','report_python','decision_dates']}
comp=[]
for ref in ['rolling5_annual20','rolling5_quarterly20','state90']:
    for m in ['learned_vol_interaction','learned_order_extension','learned_order_offset']:
        for loss in ['direction_error','brier']:comp.append(dict(history='error16',candidate=m,reference_history=ref,reference=m,metric=loss))
comp += [dict(history='error16',candidate='learned_vol_interaction',reference_history='error16',reference=m,metric=l) for m,l in [('training_frequency','brier'),('native_mse','direction_error')]]
c.update(version=30,experiment='Persistent mature out-of-sample forecast underperformance triggers quarter-end updates',
    monitor=dict(method='learned_vol_interaction',seeds='all3 equal probability mean',lookback_weeks=16,block_weeks=8,threshold=0.,loss='Brier relative to same active-cutoff training-frequency probability issued at forecast time.',rule='At non-December quarterend, select the latest16mature weekly forecasts actually issued under the currently active model. Split in chronological order into older8 and recent8. Refit iff both block-average(modelBrier-frequencyBrier)>0. Missing16 means hold. Zero means hold. Reset feedback membership whenever model cutoff changes; no stale predecessor-model errors. Shared schedule for all6methods/seeds. AnnualDec31alwaysupdates.',maturity='joint_completed<=decision cutoff, using inherited execution plus auxiliary target maturity convention. Model cutoff<signaldate; signal on decision date still uses incumbent. New selection applies strictly after decision.',warmup='Begin Jan2021 with model cutoff2020-12-31. No earlier predictions or in-sample errors borrowed. Each new model accumulates its own issued forecasts.'),
    policies=['rolling5_matched','rolling5_annual20','rolling5_quarterly20','state90','error16'],primary_comparisons_per_window=comp,
    prediction_coverage='Before adaptive simulation, precompute complete target-independent coverage: each of23R28 rolling5natural20 model cutoffs through its remaining forecast calendar year (Dec model through nextyear), same272eligibleweeks. Reuse immutable R28 and R29 outputs; only infer missing(model,date)rows, one sorted missing-row batch percutoff/seed. Preserve original native flags and feature batches. Universal coverage includes off-policy predictions; this is computational reuse, not access permission for trigger decisions.',
    sequencing='Freeze protocol/source/inputs/4600oldfiles and calendar-only coverage before new inference. Contract validates coverage, maturity filters, boundaries and synthetic feedback cases. Complete universal inference extensions first. Then run one chronological policy simulation; its decision function receives only already-issued,current-model,mature forecasts. Future and other-model feedback never enters. Freeze route/feedback ledger before aggregate evaluation. No epoch,threshold,window,seed or rule search.',
    inference='40predefined contrasts jointlyHolm:2periods*(3mainrecipes*2losses*3schedulecomparators+R19vsownfrequencyBrier and native direction).10000circular8-observation bootstrap,seed20260910,centeredtwo-sidedp,marginal95CI,negative lossdifference better. Oldmatchedannual retained descriptiveonly; allmethods/years/seeds reported. No across-round adjustment.',
    diagnostic='After policy simulation, for each of17optional decisions report incumbent and fresh-model R19 performance over nextquarter on identicaldates; label trigger,warmup and held cases. This is descriptive counterfactual diagnosis,never used to choose current or later decisions and has no additional policy ranking/significance tests.',
    verification='Replay all newly extended neural predictions and frozen-head algebra/native outputs; inherit immutable R28/R29 training/head verification. Independent chronological scalar policy replay from source seed probabilities and obs targets, exact feedback row/block membership. For each optionaldecision flip every still-unmatured label and perturb future forecast probabilities then replay prefix; events unchanged. Poison other model forecasts and non-current-model published errors before a local decision; unchanged. Synthetic insufficienthistory,positiveboth,oneblocknegative,strictzero,reset,maturity tests. Independent metrics/all40contrasts,source hashes,4600oldfiles.',
    budgets=dict(old_files=4600,new_neural_fits=0,new_head_fits=0,candidate_cutoffs=23,mandatory_refits=6,optional_checks=17,model_rows=21760,ensemble_rows=8160,weeks=272),
    limitations='A small-window persistent loss deficit is a heuristic, not a statistically validated change detector; it need not indicate increasing error or guarantee a fresh model improves. The shared monitor is R19 and may not suit R23/R25.16mature weeks require warmup, so rapid changes can be missed. All historical outcomes previously viewed; no new blind confirmation,automaticpromotion,or tradingprofit claim. Universal off-policy grid is masked by chronological decision interface.')
assert len(comp)==20;write('protocol.json',json.dumps(c,indent=2,ensure_ascii=False))
s=(O/'evaluate29.py').read_text(encoding='utf-8').replace('common29','common30').replace('len(pairs)==28','len(pairs)==40').replace('primary_contrasts=28,histories=4','primary_contrasts=40,histories=5');write('evaluate30.py',s)
s=(O/'run29.py').read_text(encoding='utf-8').replace("'score',","'extend','score',").replace('{phase}29.py','{phase}30.py');write('run30.py',s)
s=(O/'delivery29.py').read_text(encoding='utf-8').replace('common29','common30').replace("['scoring','evaluation','report']","['extension','scoring','evaluation','report']");write('delivery30.py',s)
print('R30 protocol/source generated; no new predictions or feedback-trigger decisions.')
