from pathlib import Path
import json
P=Path(__file__).resolve().parents[1];O=P/'research_v30';N=P/'research_v31';N.mkdir(exist_ok=True)
def write(n,s):(N/n).write_text(s,encoding='utf-8')
old=json.loads((O/'protocol.json').read_text(encoding='utf-8'));c={k:old[k] for k in ['label_end','windows','seeds','neural','probe','offset_probe','features','report_python','decision_dates']}
methods=['learned_vol_interaction','learned_order_extension','learned_order_offset'];new=['shadow_trial','annual_quarter_half'];comp=[]
for h in new:
    for ref in ['rolling5_annual20','rolling5_quarterly20']:
        for m in methods:
            for loss in ['direction_error','brier']:comp.append(dict(history=h,candidate=m,reference_history=ref,reference=m,metric=loss))
    comp += [dict(history=h,candidate=methods[0],reference_history=h,reference=m,metric=l) for m,l in [('training_frequency','brier'),('native_mse','direction_error')]]
for m in methods:
    for loss in ['direction_error','brier']:comp.append(dict(history=new[0],candidate=m,reference_history=new[1],reference=m,metric=loss))
assert len(comp)==34
c.update(version=31,experiment='Prospective incumbent/challenger trial with delayed promotion, and fixed annual-quarterly probability blend',
    policies=['rolling5_matched','rolling5_annual20','rolling5_quarterly20','state90','error16']+new,primary_comparisons_per_window=comp,
    shadow=dict(monitor='learned_vol_interaction',min_paired_weeks=8,rule='At each non-December quarterend compare the incumbent with the challenger launched at the preceding quarterend. Use all common actually-issued Friday forecasts since that trial start whose joint_completed<=decision. Require at least8 mature pairedweeks, challenger strictly lower mean Brier AND strictly more correct directions at probability>.5. Otherwise hold; exacttieshold. Same monitor schedule shared by all6methods and3seeds. No search over monitor,minimum,lossgate,margin orcadence.',
      issuance='During each quarter freeze the incumbent and challenger, record both forecasts on each signaldate. At quarterend assess only this pair and this just-finished trial, then launch current-cutoff model as NEXT challenger. A promotion selects the already-tested previous-quarter model, never the model just trained today. Decisions only affect signaldate>cutoff; a signal on decisiondate belongs to the previous trial.',
      annual='Initial2020-12-31 and every December reset incumbent to newly trained annual model. The new challenger is identical to this incumbent, so March holds with same_model. December ignores trial performance and resets unconditionally. September trials still issue forecasts but cannot override mandatory yearend reset.',
      expected_calendar='23 training dates,6mandatoryresets,17optionalchecks:6Marchsame_model and11potentialJune/Septemberpairdecisions. Atleast8 chosen as minimum evidence within onequarter, not an optimized threshold or a formal significance test.'),
    blend=dict(weight_annual=.5,weight_quarterly=.5,rule='At every forecastdate use latest strictly-earlier December model and latest strictly-earlier quarterend model. Average their probabilities within the same seed, then equal3seed probabilities. Frequency probabilities samehalfaverage; native raw return forecasts samehalfaverage with zero threshold and no invented probability. In Q1 models identical. No fitted weights, no adaptive routing, no future labels.',cutoff_column='For blend rows cutoff records the latest constituent training cutoff only, not a single trained model. blend_routing.csv records both constituent cutoffs and weights.'),
    coverage='Reuse immutable R30 universal_model_predictions:671modelweeks covering all23R28rolling5natural20cutoffs through forecastyearend and272canonicalweeks. No additional inference, neuralfits or headfits. Verify completecalendarcoverage and old model provenance. Trial decisions may only read paired mature actually-issued records, not universal off-policy outcomes.',
    sequencing='Freeze protocol,sources,inputs,and4696oldfiles before policy simulation. Contract tests coverage and synthetic pairs without actual policy outcomes. Then one chronological trial and deterministic halfblend; freeze events,paired ledger,trialmemberships and both routes before aggregate evaluation or following-quarter diagnostics.',
    inference='68predefinedcontrasts jointHolm:2periods*[2newpolicies*(3mainrecipes*2losses*2references+R19vsownfrequencyBrier/nativeerror)+3mainrecipes*2losses shadowvshalf].10000circular8-observation bootstrap,seed20260910,centeredtwo-sidedp,marginal95CI,negativelossdifferencebetter. State90,error16,oldmatchedannual retained descriptively. No across-round adjustment.',
    diagnostic='After policy freeze, compare evaluated challenger versus incumbent over nextquarter at each of11distinct nonannualtrial decisions, regardless of promotion. Descriptive only; never feed these future scores back into policy. Include held and promoted cases without searching for favorable subsets.',
    budgets=dict(old_files=4696,new_neural_fits=0,new_head_fits=0,new_inference_passes=0,training_cutoffs=23,network_fits_if_online=69,head_fits_if_online=276,model_rows=30464,ensemble_rows=11424,weeks=272),
    verification='Independent scalar chronological replay using source3seedprobabilities and canonicaltargets. Exact pairmembership,cutoffs,issuance,maturity and strictdirection/Briergates; perturb immaturelabels/futureprobs,unissuedmodelpredictions and stale trialrecords. Independent algebra ofhalfblend,nativeoutputandfrequency. Inherit frozenR28-30neural/head replay; verify69checkpointstates and all4696oldfiles. Recompute allmetrics and68contrasts; independent coreloss/bootstrap arithmetic and Holm.',
    limitations='All272historical outcomes and some challenger/incumbent diagnostics were seen before this round; this is exploratory historical requalification, not a new blind test. Gate selected in response to R30 probability/accuracy mismatch; no outcome search within R31. Small trial samples can be noisy and slow; dual gate is a heuristic, not statistical proof. R19 shared schedule may not suit R23/R25. Shadow requires training challengers even when rejected, so no quarterly-training-cost saving claim. Annual reset retained, including bypass of yearend trial.' )
write('protocol.json',json.dumps(c,indent=2,ensure_ascii=False))
s=(O/'evaluate30.py').read_text(encoding='utf-8').replace('common30','common31').replace("next_quarter_diagnostics(csv('feedback_pool'),csv('events'))","next_quarter_diagnostics(csv('feedback_pool'),csv('events'))").replace('len(pairs)==40','len(pairs)==68').replace('primary_contrasts=40,histories=5','primary_contrasts=68,histories=7');write('evaluate31.py',s)
s=(O/'run30.py').read_text(encoding='utf-8').replace("'extend',",'').replace('{phase}30.py','{phase}31.py');write('run31.py',s)
s=(O/'delivery30.py').read_text(encoding='utf-8').replace('common30','common31').replace("['extension','scoring','evaluation','report']","['scoring','evaluation','report']");write('delivery31.py',s)
print('R31 protocol and shared evaluation/runner created before simulation.')
