"""Prepare R29 source and protocol before observing trigger decisions."""
from pathlib import Path
import json
P=Path(__file__).resolve().parents[1];O=P/'research_v28';N=P/'research_v29'
def write(name,s):(N/name).write_text(s,encoding='utf-8')
old=json.loads((O/'protocol.json').read_text(encoding='utf-8'));c={k:old[k] for k in ['label_end','windows','seeds','neural','probe','offset_probe','features','report_python']}
comp=[]
for ref in ['rolling5_annual20','rolling5_quarterly20']:
    for m in ['learned_vol_interaction','learned_order_extension','learned_order_offset']:
        for loss in ['direction_error','brier']:comp.append(dict(history='state90',candidate=m,reference_history=ref,reference=m,metric=loss))
comp += [dict(history='state90',candidate='learned_vol_interaction',reference_history='state90',reference=m,metric=l) for m,l in [('training_frequency','brier'),('native_mse','direction_error')]]
c.update(version=29,experiment='Annual fallback plus a single causal market-state change trigger at quarter ends',decision_dates=[f['cutoff'] for f in old['folds']],
    state=dict(observations=60,percentile=.9,min_calibration_pairs=252,features=['trend60','volatility20','range20','volume_change20'],scaling='Same1/99quantile clipping and population standardization as R18, fitted using active model mature5year training rows. Apply unchanged to reference, calibration, and current states.',distance='Mean across4coordinates of squared differences of60-observation mean standardized descriptors.',reference='Last60available canonical daily signal anchors at active model cutoff, labels not required for state observation.',calibration='All pairs of60-observation mean states within the5calendar-year anchor history ending at active model cutoff, separated by same number of available daily observations as current decision minus active cutoff. Rolling windows entirely in calibration anchor history; descriptor raw60bar context can precede window lower bound. At least252 pairs.90th percentile linear interpolation.',rule='At each non-December quarterend: refit iff distance strictly exceeds calibrated90th percentile. On trigger reference/scaler resets to new model cutoff. At every December31 always refit. Events effective only for signaldates strictly after decision date. Same schedule for all methods and seeds; no target values, errors, probabilities, accuracy or model coefficients used.'),
    reuse='Reuse immutable R28 rolling5 natural20 backbones and four heads; no neural/head refits.69 preexisting networks/276heads cover all23 candidate dates. Selected schedule determines counterfactual runtime training cost. No threshold/window/seed/rule grid.',
    predictions='Reuse existing frozen R28 outputs wherever available. If a non-December model is retained beyond its formerly scored quarter, infer ONLY missing required rows in ascending order as one batch permodel/seed using frozen weights/scales. Original native requires_grad=True flag and frozen feature extraction batch128 retained. Never rewrite archived overlapping outputs. All extensions independently replayed.',
    baselines=['rolling5_matched','rolling5_annual20','rolling5_quarterly20'],policies=['rolling5_matched','rolling5_annual20','rolling5_quarterly20','state90'],primary_comparisons_per_window=comp,
    inference='28contrasts jointlyHolm:2periods*(3mainrecipes*2losses*2schedulecomparators +R19vs own frequencyBrier and native direction).10000circular8-observation bootstrap,seed20260910,centeredtwo-sidedp,marginal95percentileCI; negative loss difference better. No across-round multiplicity claim.',
    sequencing='Freeze protocol/source/input/4522oldfiles before generating trigger schedule. Freeze full state schedule and extension membership before any new inference. Contract independently reconstructs descriptors, scaler, windows, matched-lag calibration and routing without prediction/target columns. Then extend inference, evaluate and verify. All existing historical outcomes were already viewed.',
    verification='Scalar market descriptors; independent loop means/quantiles and manual clipping/std; future-feature perturbation invariance for every decision; input target columns excluded by interface; exact active-cutoff route and archived output parity; replay each extension checkpoint and feature algebra/native/heads; independent metrics and all28contrasts; preservation4522files.',
    budgets=dict(old_files=4522,new_neural_fits=0,new_head_fits=0,candidate_cutoffs=23,mandatory_refits=6,optional_checks=17,model_rows=17408,ensemble_rows=6528,weeks=272),
    limitations='This is an unsupervised mean-state change heuristic, not a validated regime classifier or a significance test. The empirical90th percentile is not a falsealarm guarantee: history pairs overlap. May miss short/transient changes and conditional predictive drift, or trigger harmless distribution changes. Quarter-end decisions only. Trigger-count and new-inference budget are derived once from observed historical features, not performance. A successful replay is not a predictive or profitability PASS. No automatic promotion.')
assert len(comp)==14;write('protocol.json',json.dumps(c,indent=2,ensure_ascii=False))
s=(O/'evaluate28.py').read_text(encoding='utf-8').replace('common28','common29').replace("e.history.eq('full')","e.history.eq('rolling5_annual20')").replace('len(pairs)==64','len(pairs)==28').replace('primary_contrasts=64,histories=7','primary_contrasts=28,histories=4')
write('evaluate29.py',s)
s=(O/'run28.py').read_text(encoding='utf-8').replace("'train',",'').replace('{phase}28.py','{phase}29.py');write('run29.py',s)
s=(O/'delivery28.py').read_text(encoding='utf-8').replace('common28','common29').replace("['training','scoring','evaluation','report']","['scoring','evaluation','report']");write('delivery29.py',s)
print('R29 source/protocol generated; no trigger schedule or new inference yet.')
