from pathlib import Path
import json
P=Path(__file__).resolve().parents[1];O=P/'research_v31';N=P/'research_v32';N.mkdir(exist_ok=True)
def write(n,s):(N/n).write_text(s,encoding='utf-8')
old=json.loads((O/'protocol.json').read_text(encoding='utf-8'));c={k:old[k] for k in ['label_end','windows','seeds','neural','probe','offset_probe','features','report_python','decision_dates']};comp=[];candidate='annual_net_quarter_head'
for ref in ['rolling5_annual20','rolling5_quarterly20']:
    for m in ['learned_vol_interaction','learned_order_extension','learned_order_offset']:
        for loss in ['direction_error','brier']:comp.append(dict(history=candidate,candidate=m,reference_history=ref,reference=m,metric=loss))
comp += [dict(history=candidate,candidate='learned_vol_interaction',reference_history=candidate,reference=m,metric=l) for m,l in [('training_frequency','brier'),('native_mse','direction_error')]]
c.update(version=32,experiment='Annual frozen neural representation with quarterly causal head-pipeline refits',policies=old['policies']+[candidate],primary_comparisons_per_window=comp,
    head_update=dict(policy=candidate,encoder='Each forecastyear uses the R28 rolling5 natural20 encoder fitted at the preceding Dec31. Reuse all18frozen annual networks; no gradients, fine-tuning or optimizer changes.',
      pipeline='At each nonDecember quarterend refit the complete low-dimensional classification pipeline on exactly the same causal rolling5 anchor-window as R28 full-quarterly: 1/99 clipping and population scaling of25decodedfeatures and4marketfeatures, supervisedR18ray, vol/order residual projections, R18/R19/R23coefficients and R25scalaroffset. R25 freezes its newly fitted same-quarter R19 coefficients. The network remains annual. No otherlambda,feature,window,threshold orseed choices.',
      annual='December head and transformations are reused exactly from the corresponding annual model; Q1 predictions must equal annual. In later quarters the annual encoder remains unchanged while head training samples roll forward. Model/label maturity joint_completed<=headcutoff. Signaldate strictly>headcutoff; signal on quarterend still uses previoushead.',
      training='Fivecalendar-year anchor window headcutoff-5years+1day through all joint-mature observations by headcutoff. Include all eligible weekdays, not just Fridays. Raw125bar context can precede anchor lowerbound. Neural target normalizations stay frozen at annual training; do not update neural scales.',
      prediction='Same272Fridayweeklycases. Learned rows cutoff=headcutoff; native_MSE cutoff=annualencodercutoff; training-frequency cutoff=headcutoff. routing.csv explicitly records encoder/head cutoffs. Native forecasts exactly frozenannual; frequency exactly fullquarterly. No probability for native.'),
    feature_bank='For each annualencoder reuse immutable R28 annual training decodedfeatures and annual full-year testing decodedfeatures. These memberships are disjoint. Form sorted union with all required quarterly head-trainingrows, extract only missing daily observations from this frozenencoder with original128batch featureextractor. Training interfaces select only head-trainingrows; testfeatures only used in scoring. Future rows existing in a computational bank are not training permission. Each bank stores source0annualtrain,1annualtest,2newextraction. No averaging of duplicate representations.',
    sequencing='Freeze protocol/sources/inputs/4759oldfiles before extraction or fitting. Contract independently verifies memberships, source cache hashes, routes, maturity boundaries and data descriptor algebra. Build banks without fitting/scoring; freeze banks. Fit51quarterencoder-seedjobs,204heads and102projections with no weekly scoring. Freeze allheads before prediction/evaluation. Independent feature replay and convex solvers plus causal interfaces must PASS.',
    budgets=dict(old_files=4759,new_neural_fits=0,annual_networks=18,new_encoder_extension_passes=18,new_head_jobs=51,new_head_fits=204,new_projections=102,reused_annual_heads=72,online_neural_fits=18,online_head_fits=276,model_rows=34816,ensemble_rows=13056,weeks=272),
    inference='28predefinedcontrasts jointlyHolm:2periods*(3mainrecipes*2losses*2references+R19vsownfrequencyBrier/nativeerror).10000circular8-observation bootstrap,seed20260910,centeredtwo-sidedp,marginal95CI,negative lossdifferencebetter. All7frozenpriorpolicies retained descriptively; allmethods/years/seeds reported. No across-round multiplicity adjustment.',
    verification='Replay each18bank extension with unchanged annualnetwork states and exactsourcefeature preservation; independently reconstruct scalers, descriptor/order gates, residualprojections and all204convexsolutions via L-BFGS-B/Brent. Compare scoring to independentexpit algebra. Perturb all future labels and all out-of-trainingbankfeature rows for each51fit interface: selected inputs unchanged. Check all6Q1segments equalannual, nativeequalannual and frequencyequalquarterly. Independent metrics,28bootstrap/Holm tests and4759oldfiles.',
    limitations='All272historical outcomes previouslyseen, including recent annual/quarterly differences; this is exploratory historical research, not a new blind test. Annual features are in-sample for some head-trainingrows, as in inherited pipeline, so no full-pipelineOOF claim. Updating all classification preprocessing/rays with head coefficients is one combined downstream intervention; result does not isolate a single coefficient or prove why a network update helps/hurts. No live orders, automaticpromotion, cost/return performance claim.')
assert len(comp)==14;write('protocol.json',json.dumps(c,indent=2,ensure_ascii=False))
s=(O/'evaluate31.py').read_text(encoding='utf-8').replace('common31','common32').replace(",next_quarter_diagnostics=next_quarter_diagnostics(csv('feedback_pool'),csv('events'))",'').replace('len(pairs)==68','len(pairs)==28').replace('primary_contrasts=68,histories=7','primary_contrasts=28,histories=8');write('evaluate32.py',s)
s=(O/'run31.py').read_text(encoding='utf-8').replace("'contract','score'","'contract','extract','fit','score'").replace('{phase}31.py','{phase}32.py');write('run32.py',s)
s=(O/'delivery31.py').read_text(encoding='utf-8').replace('common31','common32').replace("['scoring','evaluation','report']","['extraction','fitting','scoring','evaluation','report']");write('delivery32.py',s)
print('R32 protocol and generic evaluation/runner created before fitting.')
