from pathlib import Path
import json
root=Path('D:/ddos_v3/research_v38');root.mkdir(exist_ok=True);assert not (root/'results/preparation_manifest.json').exists()
old=json.loads((root.parent/'research_v37/protocol.json').read_text(encoding='utf-8'));c={k:old[k] for k in ['label_end','windows','seeds','report_python','decision_dates','states','state_definition']}
c.update(version=38,experiment='Transfer of newly mature calibration residuals from daily training to subsequent Friday signals',
    views=['daily','friday','future'],residual='r_i=y_i-p_annual_i; positive means annual probability too low on that observed sample, negative too high. Never confuse residual with y minus annual training label frequency. Ensemble r uses the equal mean of three saved annual probabilities; never sigmoid of mean logits.',
    cohorts='At each of23head cutoffs use R37 N=Q minus A. Daily is allN, friday is subset weekday=4, future is original weekly route following that cutoff through nextquarter boundary or final observed date. Q1 new sets empty and retained explicitly. No per-state selection of membership or recomputation of targets. Every comparison uses same annual representation, head and R36 boundary. Daily and Friday training cohorts are cumulative within annual and overlap across quarters; do not pool their rows as independent observations.',
    cached_only='Reuse51 R37 correction-input caches containing annual logits on N, all original model/ensemble probabilities, frozen states and correction effects. Convert saved logits to probabilities for diagnostic rows; no neural inference, new features, classifier/scalar fitting, parameter searches or new forecast policy. Labelled future summaries are retrospective only and never passed to model/correction selection.',
    decomposition='For residual mean target minus source, composition=sum((wT-wS)*rS), within=sum(wT*(rT-rS)). Report daily->friday, friday->future, daily->future at every cutoff, method and seed/ensemble. If source or target empty, undefined. If target has positive count in a state absent from source, components undefined with explicit flag; overall mean delta remains reported when both nonempty. No imputation of missing-state residual. Fixed source-first accounting is not causal.',
    transfer='Per cutoff/state/method/seed plus ensemble: train daily residual, train Friday residual, next-route Friday residual, counts and original R37 eligibility. Sign tolerance1e-12. Report same/opposite/near_zero/undefined. Aggregates use counts of cutoff-state cells and corresponding disjoint future-week coverage, never percentage accuracy or independent Bernoulli trials. Three declared cohorts: any nonempty view+future; original R37daily>=20 with view+future nonempty; and daily>=20 with Fridaytrain>=10 and future>=10. Last is descriptive sparse flag, no new policy gate. Report all six years, early147/recent125 and pooled272.',
    overlap='Use stored execution label intervals [entry,exit) in trading-bar edge coordinates. Intervals that touch only at boundary do not overlap. Report n, unique intervals, total edge uses, union edges, mean/max edge multiplicity, overlapping interval-pair count and maximum count of disjoint intervals via earliest-finish scheduling, for all5state scopes(all+4) x3views x23cutoffs. These are mechanical target-overlap measures, not effective independent sample size; even disjoint returns or Friday samples may be serially dependent. Auxiliary targets and125bar input overlap are not quantified here. Verify training/future execution intervals do not overlap.',
    metrics='Original annual accuracy,Brier,logloss,AUROC,balancedaccuracy,probability spread, up-count/down-count and calibration residual for23cutoffs x5state scopes x3views x4learnedmethods x4seedroles. seed=-1 here denotes equal-probability ensemble, not a new random seed. Empty/single-class cells explicit and AUROC/balancedaccuracy undefined if class missing. No pooling training sets for cross-year AUROC.',
    ranking='Within each cutoff/state, a constant logit shift preserves per-seed ordering. Compare archived R37 state/shared/half against annual using allpair inversion and tie-change counts and within-cell AUROC, for4methods x4seedroles x23cutoffs x4states x3policies. Ensemble may reorder because averaging differently shifted seeds is not a common monotone map of the original mean; pooled years/states can reorder. All sparse/empty cells kept.',
    brier='Use only saved weekly probabilities: delta=p_corrected-p_annual, e=y-p_annual. Exact candidate-minus-annual Brier difference=delta^2-2*delta*e. First component nonnegative, second sign reflects alignment with subsequently observed residual. Save perweek, seed and ensemble for all3R37policies; summarize by period/method/seed over allweeks and R37eligible-only. This is algebraic loss accounting, not causal proof, a deployable rule or a new prediction.',
    sequencing='Freeze8sources, protocol, inputs and5428old evidence files before diagnostics. Freeze label-free membership and overlap after causal/synthetic contract, then residual/metrics/transfer/ranking/Brier accounting once. Independent scalar metrics, interval algorithms, source probability joins, missing-state decomposition, sign tallies, ranking comparisons and old hashes before report.',
    limits='All272historical weekly outcomes viewed previously; motivated by R37 failures. Descriptive only: zero new p-values, no tuning or model selection. R37 48comparisons preserved unchanged. Original R25recent73/125=58.4% preserved separately from natural20annual71/125=56.8%. No live trading, returns strategy, state gate deployment or new training.',
    settings={'daily_count_flag':20,'weekly_count_flag':10,'residual_zero_tolerance':1e-12},
    budgets={'old_files':5428,'new_fits':0,'new_feature_inference':0,'new_forecast_policies':0,'new_inferential_tests':0,'cutoffs':23,'input_caches':51,'future_weeks':272,'overlap_cells':345,'metric_cells':5520,'transfer_cells':1472,'decomposition_cells':1104,'ranking_cells':4416})
(root/'protocol.json').write_text(json.dumps(c,indent=2,ensure_ascii=False)+'\n',encoding='utf-8');print('R38 diagnostic protocol drafted; no new outcomes summarized.')
