from pathlib import Path
import json
root=Path('D:/ddos_v3/research_v39');root.mkdir(exist_ok=True);assert not (root/'results/preparation_manifest.json').exists()
old=json.loads((root.parent/'research_v38/protocol.json').read_text(encoding='utf-8'));c={k:old[k] for k in ['label_end','windows','seeds','report_python','decision_dates','states','state_definition']}
p={'state_gated':'weekly_state_validated','state_direct':'weekly_state_ungated','global_gated':'weekly_global_validated','global_direct':'weekly_global_ungated'}
c.update(version=39,experiment='Chronological held-out mature-week validation of bounded probability corrections',policies=p,
    settings={'training_weeks':52,'validation_weeks':13,'minimum_state_train':10,'minimum_state_validation':5,'ridge_sum_lambda':20.,'absolute_logit_cap':.5,'bisection_iterations':60,'brier_improvement_tolerance':1e-12,'annual_reset':True},
    split='At every nonannual quarterly cutoff C, take last13 original annual-baseline Friday signals whose joint_completed<=C as validation. Fit cutoff is calendar day before earliest validation signal. Select last52 earlier baseline signals with joint_completed<=fit_cutoff; do not merely take52rows adjacent to validation, because nearest older label may not be mature at first validation signal. Require full52+13, otherwise exact annual fallback. Preserve all warmup and annual-reset periods. At December31 use new annual base nextQ1 without corrections, irrespective of validation. For audit, potential split counts remain recorded even when no fit is authorized by annual reset.',
    input_role='Only archived point-in-time natural20 rolling5 annual predictions on272Friday signals, with the R37 saved annual logits and original R36 signal-time states. Calibration training pools past annual model versions and their original annual-relative state labels. It does not retrospectively score older signals using the current network or current volatility median. Validation checks this sequential calibration rule on older base-model outputs, not proof that the latest/new-year network has been validated. No prior training-in-sample logits, extra daily rows or pre2021 model backfill.',
    fitting='Four learned methods,3seeds. ReuseR37scalar objective sum Bernoulli logloss(z+d)+20*d^2/2, abs(d)<=.5,60gradient bisection steps or bound optimum. Global family fits one offset perseed to all52 training weeks. State family fits one perstate perseed only if state training n>=10; otherwise zero. No class balancing or outcome-driven membership. The two families differ in support and total parameter penalty; state-vs-global is a recipe comparison, not a pure isolated state-effect ablation.',
    validation='Freeze all fit parameters before reading held-out labels. On13validation signals apply the unchanged fitted offset to original annual logits; then average3seedprobabilities equally. Global gate requires Brier lower by >1e-12 and correct direction count no lower than annual over all13. State gate applies same conditions separately only when state train>=10 and state validation>=5. Other states fallback. Direction strict>0.5, ties down. These are fixed heuristic gates, not significance or statistical qualification. No best-state/strength/seed selection. No correction refit after validation; holdout outcomes affect gates only.',
    controls='Four policies: state validated and identical fitted state offsets ungated; global validated and identical fitted global offset ungated. Ungated control isolates validation routing within each family and uses exactly same older52training members, not a refit on allrecent65. All four share warmup and annualQ1zero correction. Gate determined per method using ensemble, then applied consistently across3seeds. Native_mse and training_frequency exact annual copies. Archive16old policies intact including R37 variants.',
    scoring='At C, all gate inputs already mature, while subsequent route signals have date>C. Apply fixed selected offset to their original annual logits according to original signal state. Zero offset copies annual probability exactly. Freeze all gates before computing any subsequent candidate scores or aggregate outcome comparisons. Fitting52 and heldout13 are latestcounts, not exact calendar-year/quarter lengths; holidays and maturation delay matter.',
    sequencing='Freeze11sources,protocol,inputs and5484oldfiles. Contract freezes signalbank,52/13purged splits and support. Then fit all offsets using training-only interface; freeze. Then validation-only gate stage; freeze. Then forward scores once, evaluation, independent chronological/solver/source/gate/metric/bootstrap verification, report and delivery. No tuning after scores.',
    inference='84exploratory comparisons:4newpolicies vsannual,2validated vs ownungated, statevalidated vsglobalvalidated; each3primarymethods x2losses(directionerror,Brier) x2fixedwindows. Circular8week bootstrap10000 seed20260910 centered2sidedp, Holm across84. R18diagnostic; all6years,pooled,individualseeds andstate results kept. Correction does not cover prior research rounds/adaptive hypothesis choice. No new blind holdout claim.',
    limitations='All272outcomes previously seen; count thresholds and memory fixed now without searching newcandidate results. Latest validation is delayed and may be small bystate; positive historical validation can fail forward. Underlying annual model versions and relative state boundaries change across pooled history. Q1fallback and earlywarmup limit coverage. This is new scalar calibration, not training or deployment of a new neural model. Old R25recent73/125=58.4%, natural20annualR25 71/125=56.8%, and2025R37localgain retained separately.',
    budgets={'old_files':5484,'new_neural_fits':0,'new_transform_fits':0,'new_feature_inference':0,'weeks':272,'cutoffs':23,'new_policies':4,'maximum_scalar_fits':1020,'new_learned_seed_rows':13056,'new_total_seed_rows_with_copied_controls':17408,'total_model_rows':87040,'total_ensemble_rows':32640,'comparisons':84})
pairs=[]
for a,b in [(v,'rolling5_annual20') for v in p.values()]+[(p['state_gated'],p['state_direct']),(p['global_gated'],p['global_direct']),(p['state_gated'],p['global_gated'])]:
    for m in ['learned_vol_interaction','learned_order_extension','learned_order_offset']:
        for loss in ['direction_error','brier']:pairs.append(dict(history=a,candidate=m,reference_history=b,reference=m,metric=loss))
c['primary_comparisons_per_window']=pairs
(root/'protocol.json').write_text(json.dumps(c,indent=2,ensure_ascii=False)+'\n',encoding='utf-8');print('R39 protocol drafted; no fit, gate or new forecast.')
