from common25 import *

def main():
    check_frozen();fit=check_phase('training');assert fit['all_converged'] and fit['new_primary_fits']==24;assert not (OUT/'scoring_manifest.json').exists();run=manifest('scoring');save(OUT/'scoring_manifest.json',run)
    obs,price,returns=data();base=csv('classification_baselines');sources={s['job']:s for s in read(OUT/'source_heads.json')};forecasts=[];components=[];summaries=[]
    for h in read(OUT/'heads.json'):
        source=sources[h['source_job']];x,rows=inputs(source,'validation');pt=np.asarray(h['frozen_parent_coefficients']);joint=np.asarray(source['coefficients']);offset=design(x[:,:-1])@pt;gamma=h['gamma'];z=offset+gamma*x[:,-1];p=probability(z)
        g=base[base.cutoff.eq(h['cutoff'])].copy();np.testing.assert_array_equal(g.row_index,rows);g['method']=h['method'];g['seed']=h['seed'];g['logit']=z;g['score']=p;g['probability']=p;g['direction_up']=p>.5;forecasts.append(g)
        joint_parent=design(x[:,:-1])@np.r_[joint[:-2],joint[-1]];joint_order=x[:,-1]*joint[-2]
        for i,row in enumerate(rows):components.append(dict(job=h['job'],method=h['method'],cutoff=h['cutoff'],seed=h['seed'],row_index=int(row),date=obs.date.iloc[row],order_feature=float(x[i,-1]),frozen_base_logit=float(x[i,:-2]@pt[:-2]+pt[-1]),frozen_original_interaction_logit=float(x[i,-2]*pt[-2]),frozen_parent_logit=float(offset[i]),order_interaction_logit=float(gamma*x[i,-1]),logit=float(z[i]),joint_parent_logit=float(joint_parent[i]),joint_order_logit=float(joint_order[i]),joint_logit=float(joint_parent[i]+joint_order[i]),parent_constraint_component=float(offset[i]-joint_parent[i]),order_coefficient_component=float((gamma-joint[-2])*x[i,-1]),total_logit_difference=float(z[i]-joint_parent[i]-joint_order[i])))
        for split,values in [('training',load_npz(source)['standardized']),('validation',x)]:
            parent_z=design(values[:,:-1])@pt;zz=parent_z+gamma*values[:,-1];jparent=design(values[:,:-1])@np.r_[joint[:-2],joint[-1]];jz=jparent+joint[-2]*values[:,-1];delta_parent=parent_z-jparent;delta_order=(gamma-joint[-2])*values[:,-1]
            summaries.append(dict(job=h['job'],method=h['method'],cutoff=h['cutoff'],seed=h['seed'],split=split,n=len(values),offset_gamma=gamma,joint_gamma=float(joint[-2]),gamma_difference=float(gamma-joint[-2]),frozen_original_interaction_coefficient=float(pt[-2]),parent_coefficient_l2_drift=0.,parent_intercept_drift=0.,order_logit_sd=float((gamma*values[:,-1]).std()),parent_constraint_rms=float(np.sqrt(np.square(delta_parent).mean())),order_coefficient_change_rms=float(np.sqrt(np.square(delta_order).mean())),total_logit_difference_rms=float(np.sqrt(np.square(zz-jz).mean())),rms_probability_change_vs_parent=float(np.sqrt(np.square(probability(zz)-probability(parent_z)).mean())),rms_probability_change_vs_joint=float(np.sqrt(np.square(probability(zz)-probability(jz)).mean()))))
    new=pd.concat(forecasts,ignore_index=True);assert len(new)==1044;models=pd.concat([pd.read_csv(V24/'results/model_predictions.csv',float_precision='round_trip'),new],ignore_index=True)
    e=new.groupby(['method','date'],sort=True).agg(cutoff=('cutoff','first'),row_index=('row_index','first'),year=('year','first'),joint_completed=('joint_completed','first'),actual_return=('actual_return','first'),actual_up=('actual_up','first'),training_frequency=('training_frequency','first'),score=('score','mean'),probability=('probability','mean')).reset_index();e['direction_up']=e.probability>.5
    ensemble=pd.concat([pd.read_csv(V24/'results/ensemble_predictions.csv',float_precision='round_trip'),e],ignore_index=True);assert len(models)==15660 and len(ensemble)==9135 and ensemble.groupby('method').size().eq(261).all();files=[]
    for name,frame in dict(new_model_predictions=new,model_predictions=models,ensemble_predictions=ensemble,interaction_components=pd.DataFrame(components),component_summary=pd.DataFrame(summaries)).items():path=OUT/f'{name}.csv';frame.to_csv(path,index=False);files.append(path)
    finish(run,files,new_probability_forecasts=1044,reused_model_records=14616,model_records=15660,ensemble_records=9135,interaction_components=1044);print('Scored1044new probabilities;35methods on261dates.',flush=True)
if __name__=='__main__':main()
